config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'recipes/card_update', to: 'recipes#card_update'
  post 'recipes/form_add', to: 'recipes#form_add'
  post 'recipes/destroy_form', to: 'recipes#destroy_form'

  resources :recipes, only: %i[index new create] do
    resources :recipe_materials, only: %i[new create]
    resources :recipe_products, only: %i[new create]
  end
  resources :machines, only: %i[new create]
  resources :items, only: %i[new create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form/base.rb
class Form::Base
  include ActiveModel::Model
  include ActiveModel::Callbacks
  include ActiveModel::Validations
  include ActiveModel::Validations::Callbacks

end

app/models/form/generate_time_collection.rb
class Form::GenerateTimeCollection < Form::Base
  global = 3
  attr_accessor :recipe_materials

  def initialize(attributes = {})
    super attributes
    self.recipe_materials = global.times.map { RecipeMaterial.new() } unless self.recipe_materials.present?
  end

  def generate_times_attributes=(attributes)
    self.recipe_materials = attributes.map { |_, v| RecipeMaterial.new(v) }
  end

  def save
    RecipeMaterial.transaction do
      self.recipe_materials.map do |recipe_material|
        recipe_material.save
      end
    end
      return true
    rescue => e
      return false
  end
end

app/models/item.rb
class Item < ApplicationRecord

  mount_uploader :item_image, ItemUploader

  has_many :recipe_materials
  has_many :recipe_material_items, through: :recipe_materials, source: :recipe

  has_many :recipe_products
  has_many :recipe_product_items, through: :recipe_products, source: :recipe

end

app/models/machine.rb
class Machine < ApplicationRecord
  has_many :recipes
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_materials
  has_many :materials, through: :recipe_materials

  has_many :recipe_products
  has_many :products, through: :recipe_products

  belongs_to :machine

  accepts_nested_attributes_for :recipe_materials
  accepts_nested_attributes_for :recipe_products
end

app/models/recipe_material.rb
class RecipeMaterial < ApplicationRecord
  belongs_to :material, class_name: "Item"
  belongs_to :recipe
end

app/models/recipe_product.rb
class RecipeProduct < ApplicationRecord
  belongs_to :product, class_name: "Item"
  belongs_to :recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash.now[:success] = "セーブ成功"
      redirect_to recipes_path
    else
      flash.now[:danger] = "セーブ失敗"
      render :new
    end
  end

  private

  def item_params
    params.require(:item).permit(:item_name, :item_image)
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def new
    @machine = Machine.new
  end

  def create
    @machine = Machine.new(machine_params)
    if @machine.save
      redirect_to recipes_path, success: 'セーブできました'
    else
      flash.now[:danger] = "セーブ失敗"
      render :new
    end
  end

  private

  def machine_params
    params.require(:machine).permit(:machine_name, :electricity)
  end
end

app/controllers/recipe_materials_controller.rb
class RecipeMaterialsController < ApplicationController

  def new
    @form = Form::RecipeMaterialCollection.new
  end

  def create
    @form = Form::RecipeMaterialCollection.new(recipe_time_collection_params)
    if @form.save
      redirect_to recipes_path, notice: "登録できたよ"
    else
      flash.now[:alert] = "できんかった"
      render :new
    end
  end

  private

  def recipe_material_params
    params.require(:recipe_material).permit()
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def new
# 新しいレシピの登録
    @recipe = Recipe.new
# 同時に中間テーブルも作成する
    @recipe_material = @recipe.recipe_materials.build
    @recipe_product = @recipe.recipe_products.build
  end

  def create
    @recipe = Recipe.new(recipe_params)
# 完成物(recipe_products)中間テーブル作成のための配列を取得
    @products = Item.where(id: params[:recipe][:recipe_products])
    recipe_products_times = params[:recipe][:recipe_products_time]
# @productsとrecipe_products_timeの配列を順番に合成  [["完成物１",10],["完成物２",20]]  と言う配列ができる。
  # @recipeのproducts配列に追加  同じく、@recipeのrecipe_products配列に追加。（products配列と順番が狂わないように場所の調整）（timeの未入力に対応）

    @products.zip(recipe_products_times) do |product, recipe_products_time|
      @recipe.products << [product]
      @recipe.recipe_products[@recipe.products.size - 1].product_time = recipe_products_time.to_f
    end

# 素材（recipe_materials)についても同様な処理を実行
    @materials = Item.where(id: params[:recipe][:recipe_materials])
    recipe_materials_times = params[:recipe][:recipe_materials_time]
    @materials.zip(recipe_materials_times) do |material, recipe_materials_time|
      @recipe.materials << [material]    
      @recipe.recipe_materials[@recipe.materials.size - 1].material_time = recipe_materials_time.to_f
    end

    if @recipe.save
      flash[:success] = "セーブ完了！"
      redirect_to recipes_path
    else
      flash[:danger] = "セーブできていないよ"
      redirect_to recipes_path
    end
  end

  def index
# formが増えてもrecipe_cardを区別する為の変数
    $global = 0
# formの追加の場所を決める為の変数
    @count_a = 0
    @count_b = 0
    @count_c = 0
    @button_count = "#{@count_c}-#{@count_b}-#{@count_a}"
    @recipe = Recipe.find(1)
    if params[:recipe_id].present?
      @recipe = Recipe.find(params[:recipe_id])
    end
  end

  def card_update
# どのカードをupdateするか区別する
    @global = params[:global]
    @recipe = Recipe.find(params[:recipe_id])
# ajaxでupdate
    respond_to do |format|
      format.js
    end
  end

  def form_add
    $global += 1
    @recipe = Recipe.find(1)

    count_c, count_b, count_a = params[:button_count].split('-').map(&:to_i)
# どのボタンが押されたか区別し、場所に応じて追加場所を決定する。
    if count_b == 0 # 一列目のボタンであるなら ２列目用の@button_count_nと１列目用の@button_count_oを作成
      @button_count_n = "#{count_c}-#{count_b + 1}-#{count_a}"
      @button_count_o = "#{count_c}-#{count_b}-#{count_a + 1}"
    elsif count_b > 0 && count_c == 0 # ２列目で生成されたボタンなら
      @button_count_n = "#{count_c + 1}-#{count_b}-#{count_a}"
      @button_count_o = "#{count_c}-#{count_b + 1}-#{count_a}"
    end
    @button_count = "#{count_c}-#{count_b}-#{count_a}"
# ajaxで追加する
    respond_to do |format|
      format.js
    end
  end

  def destroy_form
    $global = params[:global].to_i
  end

private

  def recipe_params
    params.require(:recipe).permit(:recipe_name, :machine_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generate_times_helper.rb
module GenerateTimesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/items/new.html.erb
<div class="container">
  <%= simple_form_for @item do |f| %>
    <div class="card" style="max-width: 222px;">
      <div class="row g-0">
        <h5 class="text-center">素材1</h5>
        <div class="col-3 align-items-center d-flex">
        </div>
        <div class="col-9">
          <div class="card-body text-muted">
            <%= f.input :item_name, input_html: { style: "width: 100%; height: 23px; margin-bottom: 5px;" }%>
            <% # 画像ファイル選択ボタンを装飾 %>
            <%= f.file_field :item_image %>
          </div>
        </div>
      </div>
    </div>
    <%= f.submit "登録", class: "btn btn-outline-dark" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Satisfactory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/machines/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= simple_form_for @machine do |f| %>
        <div class="card" style="max-width: 222px;">
          <div class="row g-0">
            <h5 class="text-center">機械</h5>
            <div class="col-5 col-sm-3">
              <img src="assets/images/default.png" class="img-fluid w-100" alt="card-horizontal-image">
            </div>
            <div class="col-7 col-sm-8">
              <div class="card-body text-muted">
                <%= f.input :machine_name, input_html: { style: "width: 100%; height: 23px;" } %>
                <%= f.input :electricity, input_html: { style: "width: 100%; height: 23px;" } %>
              </div>
            </div>
          </div>
        </div>
        <%= f.submit "登録", class: "btn btn-outline-dark"%>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_machine.html.erb
<%= fields_for :machines do |g| %>
  <div class="card" style="max-width: 222px;">
    <div class="row g-0">
      <h6 class="text-center card_title_font_size">機械</h6>
      <div class="col-3 align-items-center d-flex">
      </div>
      <div class="col-9 col-sm-8">
        <div class="col-11 card_font_size">
          <%= g.label :machine_name %>
          <div class="form-control form-control-sm card_font_size">
            <%= machine.machine_name %>
          </div>
          <%= g.label :electricity %>
          <div class="form-control form-control-sm card_font_size electricity_<%= @global %>", default_electricity="<%= machine.electricity %>", id="electricity_<%= @global %>">
            <%= machine.electricity %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe_card.html.erb
<div id="recipe_card_<%= global %>">
  <%= form_with(url: recipes_card_update_path(global: global), local: false, method: :post, id: "recipe_name_form_#{global}") do |f| %>
    <div class="card">
      <div class="card-header">
        <div class="col-8", id="js_recipe_name_<%= global %>">
          <%= f.select :recipe_id, options_for_select(Recipe.pluck(:recipe_name, :id), selected: @recipe.id),{}, class: "js_recipe_name_#{global}" %>
        </div>
      </div>
      <div class="card-body overflow-auto" style="resize: both; min-width: 200px">
        <div class="row  align-items-center" style="min-width: 500px">
          <div class="col-md-4">
            <div id="product_item_name_<%= $global %>">
              <%= render partial: "recipe_product", locals: { products: @recipe.recipe_products} %>
            </div>
          </div>
          <div class="col-md-4">
            <div id="machine_item_name_<%= $global %>">
              <%= render partial: "machine", locals: { machine: @recipe.machine } %>
            </div>
          </div>
          <div class="col-md-4">
            <div id="material_item_name_<%= $global %>">
              <%= render partial: "recipe_material", locals: { materials: @recipe.recipe_materials } %>
            </div>
          </div>
        </div>
      </div>
      <div class="text-center">
        <%= f.button "登録", type: "button", onclick: "submit();", class: "btn btn-outline-dark", style: "display:none;", id: "js_button_#{global}", data: {disable_with: false} %>
      </div>
    </div>
  <% end %>
  <div class="form_<%= button_count %>">
    <%= form_with url: recipes_form_add_path(global: $global, button_count: button_count), local: false, html:{ class: "class_name"}, method: :post do |p| %>
      <div class="add-form-button_<%= button_count %>", id="add-form-button_<%= button_count %>">
        <%= p.submit "レシピの追加", class: "add_form_button" %>
        <%= p.hidden_field :hidden %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_recipe_material.html.erb
<% number = 0 %>
<% materials.each do |m| %>
  <%= fields_for :recipe_materials do |g| %>
    <div class="card" style="max-width: 222px;">
      <div class="row g-0">
        <h6 class="text-center card_title_font_size">素材</h6>
        <div class="col-3 align-items-center d-flex">
          <%= image_tag m.material.item_image.url, id: 'preview', size: '50x50', class: "mx-auto d-flex" %>
        </div>
        <div class="col-9 col-sm-8">
          <div class="col-11 card_font_size">
            <%= g.label :material_name %>
            <div class="form-control-sm form-control card_font_size">
              <%= m.material.item_name %>
            </div>
            <%= g.label :material_time %>
            <div class="form-control-sm form-control card_font_size material_time_<%= @global %>", default_time="<%= m.material_time %>", id="material_time_<%= @global %>_<%= number %>">
              <%= m.material_time %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% number += 1 %>
<% end %>

app/views/recipes/_recipe_product.html.erb
<% number = 0 %>
<% products.each do |m| %>
  <%= fields_for :recipe_product do |g| %>
    <div class="card" style="max-width: 222px;">
      <div class="row g-0">
        <h6 class="text-center card_title_font_size">完成物</h6>
        <div class="col-3 align-items-center d-flex">
          <%= image_tag m.product.item_image.url, id: 'preview', size: '50x50', class: "mx-auto d-flex" %>
        </div>
        <div class="col-9 col-sm-8">
          <div class="col-11 card_font_size">
            <%= g.label :product_name %>
            <div class="form-control form-control-sm card_font_size">
              <%= m.product.item_name %>
            </div>
            <%= g.label :product_time %>
            <%= g.number_field :product_time, value: m.product_time, class: "form-control form-control-sm card_font_size product_time_#{@global}",default_time: "#{m.product_time}", id: "time_#{@global}_#{number}" %>
            <%= text_field_tag :product_time, '', style: 'display:none;' %>
        </div>
      </div>
    </div>
  <% end %>
  <% number += 1 %>
<% end %>
   

app/views/recipes/card_update.js.erb
// controllerでどのカードかは特定済なので、そのカードの内容をupdate
$("#product_item_name_<%= @global %>").html("<%= j(render partial: 'recipes/recipe_product', locals: { products: @recipe.recipe_products }) %>");

$("#material_item_name_<%= @global %>").html("<%= j(render partial: 'recipes/recipe_material', locals: { materials: @recipe.recipe_materials }) %>");

$("#machine_item_name_<%= @global %>").html("<%= j(render partial: 'recipes/machine', locals: { machine: @recipe.machine }) %>");

app/views/recipes/destroy_form.js.erb
var global = '<%= $global %>';
debugger;
console.log(global)
$('#recipe_card_<%= $global %>').html('');

app/views/recipes/form_add.js.erb
// controllerでどこにカードを追加するかは特定済なので、カードを追加する(ボタンも含む)
$('.card_wrapper_<%= @button_count_n %>').prepend('<%= j(render partial: "recipe_card", locals: { recipe: @recipe, global: $global, button_count: @button_count_n}) %>');
// ルールに従って自分のボタンの名前を変更する。
var newForm = `
  <div class="form_<%= @button_count_o %>">
    <%= form_with url: recipes_form_add_path(global: $global, button_count: @button_count_o), local: false, html:{ class: @button_count_o}, method: :post do |p| %>
      <div class="add-form-button_<%= @button_count_o %>", id="add-form-button_<%= @button_count_o %>">
        <%= p.submit "レシピの追加", class: "add_form_button" %>
        <%= p.hidden_field :button, { value: @button_count_o } %>
      </div>
    <% end %>
  </div>
`;

$('.form_<%= @button_count %>').replaceWith(newForm);

app/views/recipes/index.html.erb
<div class="column-0">
  <div class="d-flex card_wrapper_0-0-0 align-items-center">
    <%= render partial: "recipe_card", locals: { recipe: @recipe, global: $global, button_count: @button_count} %>
    <div class="column-1">
      <div class="d-flex card_wrapper_0-1-0 align-items-center">
        <div class="column-2">
          <div class="d-flex card_wrapper_1-1-0 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-2-0 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-3-0 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-4-0 align-items-center">
          </div>
        </div>
      </div>
      <div class="d-flex card_wrapper_0-1-1 align-items-center">
        <div class="column-2">
          <div class="d-flex card_wrapper_1-1-1 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-2-1 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-3-1 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-4-1 align-items-center">
          </div>
        </div>
      </div>
      <div class="d-flex card_wrapper_0-1-2 align-items-center">
        <div class="column-2">
          <div class="d-flex card_wrapper_1-1-2 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-2-2 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-3-2 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-4-2 align-items-center">
          </div>
        </div>
      </div>
      <div class="d-flex card_wrapper_0-1-3 align-items-center">
        <div class="column-2">
          <div class="d-flex card_wrapper_1-1-3 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-2-3 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-3-3 align-items-center">
          </div>
          <div class="d-flex card_wrapper_1-4-3 align-items-center">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container table-responsive">
  <div class="row">
    <div class="col">
      <%= simple_form_for @recipe, html: { novalidate: true } do |f| %>
        <div class="card">
          <div class="card-header">
            <div class="container">
              <div class="row">
                <div class= "col">
                  <%= f.input :recipe_name %>
                </div>
              </div>
            </div>
          </div>
          <div class="row align-items-center">
<%# -- 完成物のカード -- #%>
            <div class="col-md-4">
              <% 2.times do %>
                <div class="card" style="max-width: 222px;">
                  <div class="row g-0">
                    <h5 class="text-center">完成物</h5>
                    <div class="col-5 col-sm-4">
                      <img src="assets/images/default.png" class="img-fluid w-100" alt="card-horizontal-image">
                    </div>
                    <div class="col-5 col-sm-8">
                      <%= f.simple_fields_for :recipe_products_attributes do |p| %>
                        <div class="card-body text-muted">
                          <%= p.input :recipe_products, as: :select, collection:(Item.pluck(:item_name, :id)),input_html: { name: 'recipe[recipe_products][]' } %>
                          <%= f.simple_fields_for @recipe_product do |fm| %>
                            <%= fm.input :product_time, input_html: { name: 'recipe[recipe_products_time][]', style: "width: 100%"}%>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
<%# -- 機械のカード -- #%>
            <div class="col-md-4">
              <div class="card" style="max-width: 222px;">
                <div class="row g-0">
                  <h5 class="text-center">機械</h5>
                  <div class="col-5 col-sm-3">
                    <img src="assets/images/default.png" class="img-fluid w-100" alt="card-horizontal-image">
                  </div>
                  <div class="col-7 col-sm-8">
                    <div class="card-body text-muted">
                      <%= f.input :machine_id, as: :select, collection: (Machine.pluck(:machine_name, :id))%>
                    </div>
                  </div>
                </div>
              </div>  
            </div>
<%# -- 素材のカード -- #%>
            <div class="col-md-4">
              <% 4.times do %>
                <div class="card" style="max-width: 222px;">
                  <div class="row g-0">
                    <h5 class="text-center">素材</h5>
                    <div class="col-5 col-sm-4">
                      <img src="assets/images/default.png" class="img-fluid w-100" alt="card-horizontal-image">
                    </div>
                    <div class="col-5 col-sm-8">
                      <%= f.simple_fields_for :recipe_materials_attributes do |g| %>
                        <div class="card-body text-muted">
                          <%= g.input :recipe_materials, as: :select, collection:(Item.pluck(:item_name, :id)),input_html: { name: 'recipe[recipe_materials][]' } %>
                          <%= f.simple_fields_for @recipe_material do |fm| %>
                            <%= fm.input :material_time, input_html: { name: 'recipe[recipe_materials_time][]', style: "width: 100%"} %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "登録", class: "btn btn-outline-dark", style: "width: 33%" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class= "container">
    <div class="title_header">
      <p>Satisfactory create</p>
    </div>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
  </div>
</header>